**Numpy**

In [1]:
import numpy as np

In [ ]:
# nupy array oluşturma
# liste = [1,2,3,4,5,6,7,8,9,10]
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
dizi


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# array boyutu
dizi.shape # (15, ) 15x1 lik vektör

(15,)

In [ ]:
# 15x1 lik bir arrayi 3x5 lik bir matrise cevirelim
dizi2 = dizi.reshape(3,5)
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
print("shape:", dizi2.shape)
print("dimension:",dizi2.ndim)
print("size:",dizi2.size)
print("type:",type(dizi2))

shape: (3, 5)
dimension: 2
size: 15
type: <class 'numpy.ndarray'>


In [ ]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,7]])
dizi2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10,  7]])

In [ ]:
# sıfırlardan oluşan bir array
sifir_dizi = np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# birlerden oluşan bir array
bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# boş  bir array
bos_dizi = np.empty((2,4))
bos_dizi

array([[5.02610095e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
# arange(x,y, basamak): x den başlar y dahil değil, bsaak kadar artarak ilerler
dizi_aralik= np.arange(10,50,5)
dizi_aralik

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# linspace: x ve y dahil, basamak kadar sayiya böler
dizi_bosluk = np.linspace(10,50,100)
dizi_bosluk

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

**Numpy Temel Operasyonları**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
print("toplama:", a + b)
print("çıkarma:", a - b)

toplama: [ 6  8 10 12]
çıkarma: [-4 -4 -4 -4]


In [ ]:
# filtreleme
a = np.array([1,2,3,4])
filtre = a < 3
filtre


array([ True,  True, False, False])

In [ ]:
# matris çarpimi
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
c = a.dot(b)


In [ ]:
# matrisinin transpose (tersine çevrilmiş) hali
a = np.array([[1,2,3],[4,5,6]]) # 2x3
b = np.array([[1,2],[3,4],[5,6]]) # 2x3 -> T -> 3x2
a.dot(a.T)


array([[14, 32],
       [32, 77]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.sum())
print(a.max())
print(a.min())
print(a.mean)

21
6
1
<built-in method mean of numpy.ndarray object at 0x7f9bc92635d0>


In [ ]:
# satırları kendi arasında toplama
a.sum(axis = 0 )

array([5, 7, 9])

In [ ]:
# sqrt
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# square
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# rastgele sayi üretme
rastgele_dizi = np.random.random((3,3)) # normal dağılıma göre 0 -1 aralığında rastgele değerler
rastgele_dizi

array([[0.24150922, 0.37633787, 0.44931571],
       [0.2806052 , 0.81774412, 0.48733861],
       [0.42898928, 0.96789778, 0.23986521]])

In [ ]:
rastgele_dizi = np.random.normal(0, 1 ,5) # normal dağılıma göre 0 ortalamalı, 1 standart sapmalı değerler
rastgele_dizi

array([-0.04112434, -0.02796109, -0.01404938,  0.87697763,  0.38424422])

**indexleme ve slicing**

In [ ]:
dizi = np.array([1,2,3,4,5,6,7])
dizi[0]

1

In [ ]:
dizi[0:3]

array([1, 2, 3])

In [ ]:
dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
dizi2D[0,0]

1

In [ ]:
dizi2D[1,(0,1,2,3,4)]

array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[1, :]


array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[:, 2]

array([3, 8])

In [ ]:
dizi2D[-1, :]

array([ 6,  7,  8,  9, 10])

**Dizi manipulation**

In [ ]:
dizi2D= np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
dizi2D.shape

(2, 5)

In [ ]:
dizi2D_sahpe= dizi2D.shape
dizi2D_sahpe

(2, 5)

In [ ]:
print(dizi2D.reshape(dizi2D_sahpe[0]*dizi2D_sahpe[1])) # vektöre çeviriyoruz

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(dizi2D.reshape(dizi2D_sahpe[0]* dizi2D_sahpe[1],-1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [ ]:
dizi2D.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
"""
1) a Dizisi: İki boyutlu bir NumPy dizisi oluşturun, boyutu (3, 5) olsun.
2) b Dizisi: Tek boyutlu bir NumPy dizisi oluşturun, boyutu (15,) olsun.
3) b Dizisinin Yeniden Şekillendirilmesi: b dizisini (3, 5) boyutunda olacak şekilde yeniden şekillendirin.
4) c = a + b
5) d: np.linspace fonksiyonunu kullanarak (3, 5) boyutunda bir NumPy matrisi oluşturun.
   e: np.arange fonksiyonunu kullanarak (3, 5) boyutunda bir NumPy matrisi oluşturun.
6) f = d + e
7) c ve f dizilerinin her bir elemanını satır bazında çarpın. Sonuçları (15, 1) boyutundaki g dizisini dolduracak şekilde bir for döngüsü kullanarak elde edin.
8) c ve f dizilerini (15, 1) boyutuna yeniden şekillendirin.
   Yeniden şekillendirilen c dizisinin ilk elemanı ile f dizisinin son elemanını toplayın.
9) Elde edilen toplam değerleri kontrol edin:
   Eğer toplam 1'den büyükse, g1 isimli bir listeye ekleyin.
   Aksi takdirde, g2 isimli bir listeye ekleyin
"""
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b = b.reshape(3,5)
c = a + b
print("c: ",c)

c:  [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [ ]:
d = np.linspace(10,50,15).reshape(3,5)
print("d: ",d)
e = np.arange(10,160,10).reshape(3,5)
print("e: ",e)
f = d + e
print("f: ",f)
# f
# print("c shape:", c.shape)
# print("f shape:", f.shape)


d:  [[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]
e:  [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
f:  [[ 20.          32.85714286  45.71428571  58.57142857  71.42857143]
 [ 84.28571429  97.14285714 110.         122.85714286 135.71428571]
 [148.57142857 161.42857143 174.28571429 187.14285714 200.        ]]


In [ ]:
g = []
for i in range(c.shape[0]):
    for j in range(c.shape[1]):
        g.append(c[i, j] * f[i, j])
print("g shape: ",np.array(g).shape)

g shape:  (15,)


In [ ]:
c = c.reshape(15,1)
f = f.reshape(15,1)
f =f[::-1]
g1 = []
g2 = []
for i in range(len(c)):
    toplam = c[i] + f[i]
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
print("g1 (Toplam > 1 olanlar):", g1)
print("g2 (Toplam <= 1 olanlar):", g2)


g1 (Toplam > 1 olanlar): []
g2 (Toplam <= 1 olanlar): []


**Stacking**

In [2]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [3]:
array2 = np.array([[-1,-2],[-3,-4]])
array2

array([[-1, -2],
       [-3, -4]])

In [4]:
array_vertical =np.vstack((array1,array2))
array_vertical

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [5]:
array_horizontal = np.hstack((array1,array2))
array_horizontal

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [6]:
# problem: 2 boyutlu 3 array oluştur.
# yatayda ve dikeyde birleştir.
example_array1 = np.array([[1,2],[3,4]])
example_array2 = np.array([[-1,-2],[-3,-4]])
example_array3 = np.array([[5,6],[7,8]])

In [7]:
exapmle_array_vertical =np.vstack((example_array1,example_array2,example_array3))
exapmle_array_vertical

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4],
       [ 5,  6],
       [ 7,  8]])

In [8]:
example_array_horizontal = np.hstack((example_array1,example_array2,example_array3))
print(example_array_horizontal)

[[ 1  2 -1 -2  5  6]
 [ 3  4 -3 -4  7  8]]
